version: '2'
services:
  app:
    build: .
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/swdb
      - SWAPI_URL=https://swapi.co/api/
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGODB_PRIMARY_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=123456